#!/bin/sh

BRANDING_COMPANY_NAME_LEGAL=Citrix\ Systems,\ Inc.
BRANDING_COMPANY_NAME_SHORT=Citrix
BRANDING_PRODUCT_BRAND=XenServer
BRANDING_COMPANY_URL=www.citrix.com
BRANDING_FOLDER_PREFIX=wlb
BRANDING_PRODUCT_VERSION=7.0.0
BRANDING_RPM_NAME=citrix-wlb