language: c
os: windows
install:
  # package support for windows is not great; this is ugly, but will do for now
  - choco install cyg-get
  - cyg-get.bat aspell aspell-en
  - powershell 'Set-ExecutionPolicy -ExecutionPolicy ByPass'
script:
  - powershell './scripts/check_copyright.ps1 -NOISY'
  - powershell './scripts/check_i18n.ps1 -NOISY'
  - powershell '$env:Path+=";C:\tools\cygwin\bin"; ./scripts/check_spelling.ps1 -NOISY'
