//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvisibleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvisibleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenAdmin.InvisibleMessages", typeof(InvisibleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}/index.html?transactionID={1}.
        /// </summary>
        public static string ACTIVATION_FORM_URL {
            get {
                return ResourceManager.GetString("ACTIVATION_FORM_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activate.vmd.citrix.com.
        /// </summary>
        public static string ACTIVATION_SERVER {
            get {
                return ResourceManager.GetString("ACTIVATION_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}/reactivation_server.php.
        /// </summary>
        public static string ACTIVATION_URL {
            get {
                return ResourceManager.GetString("ACTIVATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://updates.xensource.com/[XenServer]/{0}/XenCenter.
        /// </summary>
        public static string CHECK_FOR_UPDATES_URL {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://xenserver.org/.
        /// </summary>
        public static string COMMUNITY_URL {
            get {
                return ResourceManager.GetString("COMMUNITY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cis.citrix.com/legal/.
        /// </summary>
        public static string HEALTH_CHECK_PRIVACY_STATEMENT_URL {
            get {
                return ResourceManager.GetString("HEALTH_CHECK_PRIVACY_STATEMENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver.
        /// </summary>
        public static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.mht.
        /// </summary>
        public static string HOMEPAGE_FILENAME {
            get {
                return ResourceManager.GetString("HOMEPAGE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.citrix.com/xenserverenterprise.
        /// </summary>
        public static string HTTP_LICENSES {
            get {
                return ResourceManager.GetString("HTTP_LICENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/article/CTX141433.
        /// </summary>
        public static string ISL_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("ISL_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iso.
        /// </summary>
        public static string ISO_UPDATE {
            get {
                return ResourceManager.GetString("ISO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserverenterprise.
        /// </summary>
        public static string LICENSE_EXPIRY_WEBPAGE {
            get {
                return ResourceManager.GetString("LICENSE_EXPIRY_WEBPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/downloads/licensing/license-server.
        /// </summary>
        public static string LICENSE_SERVER_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("LICENSE_SERVER_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [XenCenter].log.
        /// </summary>
        public static string LOG_FILENAME {
            get {
                return ResourceManager.GetString("LOG_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -mapid {0} {1}.
        /// </summary>
        public static string MAINWINDOW_HELP_PARAMS {
            get {
                return ResourceManager.GetString("MAINWINDOW_HELP_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help\XenCenter.chm.
        /// </summary>
        public static string MAINWINDOW_HELP_PATH {
            get {
                return ResourceManager.GetString("MAINWINDOW_HELP_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.htm.
        /// </summary>
        public static string MAINWINDOW_HOME_PATH {
            get {
                return ResourceManager.GetString("MAINWINDOW_HOME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserverenterprise.
        /// </summary>
        public static string OUT_OF_DATE_WEBSITE {
            get {
                return ResourceManager.GetString("OUT_OF_DATE_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/buy/partnerlocator.html.
        /// </summary>
        public static string PARTNEROFFERS_URL {
            get {
                return ResourceManager.GetString("PARTNEROFFERS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wiki.xenserver.org/XenCenter_Plugins.
        /// </summary>
        public static string PLUGINS_URL {
            get {
                return ResourceManager.GetString("PLUGINS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://citrix.com/English/aboutCitrix/legal/privacyStatement.asp?ntref=hp_nav_US.
        /// </summary>
        public static string PRIVACY {
            get {
                return ResourceManager.GetString("PRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/.
        /// </summary>
        public static string SUPPORT_URL {
            get {
                return ResourceManager.GetString("SUPPORT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/ad.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_AD {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/alerts.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_ALERTS {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_ALERTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/storagemigration.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_CPM {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/cpus.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_CPUMASKING {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_CPUMASKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/dmc.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_DMC {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_DMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/dr.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_DR {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/storage.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_ENHANCEDSR {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_ENHANCEDSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_GENERAL {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/gpu.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_GPU {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/ha.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_HA {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_HA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/performance.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_PERFORMANCE {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/rbac.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_RBAC {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_RBAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/vapps.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VM_APPLIANCES {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VM_APPLIANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/vmpr.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VM_PROTECTION {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VM_PROTECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UPSELL_LEARNMOREURL_VMSS {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_VMSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/xenserver/le/features/wlb.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_WLB {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_WLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.citrix.com/XSInProduct.
        /// </summary>
        public static string UPSELL_SA {
            get {
                return ResourceManager.GetString("UPSELL_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/article/CTX137335.
        /// </summary>
        public static string VMPR_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("VMPR_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/article/CTX137334.
        /// </summary>
        public static string WSS_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("WSS_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xensearch.
        /// </summary>
        public static string XEN_SEARCH {
            get {
                return ResourceManager.GetString("XEN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsupdate.
        /// </summary>
        public static string XEN_UPDATE {
            get {
                return ResourceManager.GetString("XEN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/TryXenDesktop.
        /// </summary>
        public static string XENDESKTOP_URL {
            get {
                return ResourceManager.GetString("XENDESKTOP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://updates.xensource.com/XenServer/updates.xml.
        /// </summary>
        public static string XENSERVER_UPDATE_URL {
            get {
                return ResourceManager.GetString("XENSERVER_UPDATE_URL", resourceCulture);
            }
        }
    }
}
