//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InvisibleMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvisibleMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenAdmin.InvisibleMessages", typeof(InvisibleMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cis.citrix.com.
        /// </summary>
        public static string CIS_URL {
            get {
                return ResourceManager.GetString("CIS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://support.citrix.com/xencenterclientiddownload.
        /// </summary>
        public static string CLIENT_ID_URL {
            get {
                return ResourceManager.GetString("CLIENT_ID_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.citrix.com/en-us/citrix-hypervisor/whats-new/removed-features.html.
        /// </summary>
        public static string DEPRECATION_URL {
            get {
                return ResourceManager.GetString("DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cis.citrix.com/legal/.
        /// </summary>
        public static string HEALTH_CHECK_PRIVACY_STATEMENT_URL {
            get {
                return ResourceManager.GetString("HEALTH_CHECK_PRIVACY_STATEMENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://docs.citrix.com/en-us/xencenter/.
        /// </summary>
        public static string HELP_URL {
            get {
                return ResourceManager.GetString("HELP_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?utm_campaign={0}&amp;utm_medium=ui_link&amp;utm_source={1}.
        /// </summary>
        public static string HELP_URL_QUERY {
            get {
                return ResourceManager.GetString("HELP_URL_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.citrix.com/products/citrix-hypervisor.
        /// </summary>
        public static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.mht.
        /// </summary>
        public static string HOMEPAGE_FILENAME {
            get {
                return ResourceManager.GetString("HOMEPAGE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/article/CTX141433.
        /// </summary>
        public static string ISL_DEPRECATION_URL {
            get {
                return ResourceManager.GetString("ISL_DEPRECATION_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.citrix.com/dr_product/citrix-hypervisor-subscription.
        /// </summary>
        public static string LICENSE_EXPIRY_WEBPAGE {
            get {
                return ResourceManager.GetString("LICENSE_EXPIRY_WEBPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/downloads/licensing/license-server.
        /// </summary>
        public static string LICENSE_SERVER_DOWNLOAD_LINK {
            get {
                return ResourceManager.GetString("LICENSE_SERVER_DOWNLOAD_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [XenCenter].log.
        /// </summary>
        public static string LOG_FILENAME {
            get {
                return ResourceManager.GetString("LOG_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.htm.
        /// </summary>
        public static string MAINWINDOW_HOME_PATH {
            get {
                return ResourceManager.GetString("MAINWINDOW_HOME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.citrix.com/downloads/citrix-hypervisor.
        /// </summary>
        public static string OUT_OF_DATE_WEBSITE {
            get {
                return ResourceManager.GetString("OUT_OF_DATE_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/buy/partnerlocator.html.
        /// </summary>
        public static string PARTNEROFFERS_URL {
            get {
                return ResourceManager.GetString("PARTNEROFFERS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/xenserver/xencenter-samples.
        /// </summary>
        public static string PLUGINS_URL {
            get {
                return ResourceManager.GetString("PLUGINS_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://citrix.com/English/aboutCitrix/legal/privacyStatement.asp?ntref=hp_nav_US.
        /// </summary>
        public static string PRIVACY {
            get {
                return ResourceManager.GetString("PRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.citrix.com/en-us/citrix-hypervisor/system-requirements/guest-os-support.html.
        /// </summary>
        public static string PV_GUESTS_CHECK_URL {
            get {
                return ResourceManager.GetString("PV_GUESTS_CHECK_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://support.citrix.com/.
        /// </summary>
        public static string SUPPORT_URL {
            get {
                return ResourceManager.GetString("SUPPORT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fileservice.citrix.com/api/session/token.
        /// </summary>
        public static string TOKEN_API_URL {
            get {
                return ResourceManager.GetString("TOKEN_API_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.citrix.com/products/citrix-hypervisor/get-started.html.
        /// </summary>
        public static string UPSELL_LEARNMOREURL_TRIAL {
            get {
                return ResourceManager.GetString("UPSELL_LEARNMOREURL_TRIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.citrix.com/dr_product/citrix-hypervisor-subscription.
        /// </summary>
        public static string UPSELL_SA {
            get {
                return ResourceManager.GetString("UPSELL_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xensearch.
        /// </summary>
        public static string XEN_SEARCH {
            get {
                return ResourceManager.GetString("XEN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsupdate.
        /// </summary>
        public static string XEN_UPDATE {
            get {
                return ResourceManager.GetString("XEN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.citrix.com/TryXenDesktop.
        /// </summary>
        public static string XENDESKTOP_URL {
            get {
                return ResourceManager.GetString("XENDESKTOP_URL", resourceCulture);
            }
        }
    }
}
