//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenAdmin.DotNetVnc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenAdmin.DotNetVnc.KeyMap", typeof(KeyMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff3d.
        /// </summary>
        internal static string ALL_CANDIDATES {
            get {
                return ResourceManager.GetString("ALL_CANDIDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff2f.
        /// </summary>
        internal static string ALPHANUMERIC {
            get {
                return ResourceManager.GetString("ALPHANUMERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff08.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff37.
        /// </summary>
        internal static string CODE_INPUT {
            get {
                return ResourceManager.GetString("CODE_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffe3.
        /// </summary>
        internal static string ControlKey {
            get {
                return ResourceManager.GetString("ControlKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe56.
        /// </summary>
        internal static string DEAD_ABOVEDOT {
            get {
                return ResourceManager.GetString("DEAD_ABOVEDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe58.
        /// </summary>
        internal static string DEAD_ABOVERING {
            get {
                return ResourceManager.GetString("DEAD_ABOVERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe51.
        /// </summary>
        internal static string DEAD_ACUTE {
            get {
                return ResourceManager.GetString("DEAD_ACUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe55.
        /// </summary>
        internal static string DEAD_BREVE {
            get {
                return ResourceManager.GetString("DEAD_BREVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5a.
        /// </summary>
        internal static string DEAD_CARON {
            get {
                return ResourceManager.GetString("DEAD_CARON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5b.
        /// </summary>
        internal static string DEAD_CEDILLA {
            get {
                return ResourceManager.GetString("DEAD_CEDILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe52.
        /// </summary>
        internal static string DEAD_CIRCUMFLEX {
            get {
                return ResourceManager.GetString("DEAD_CIRCUMFLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe57.
        /// </summary>
        internal static string DEAD_DIAERESIS {
            get {
                return ResourceManager.GetString("DEAD_DIAERESIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe59.
        /// </summary>
        internal static string DEAD_DOUBLEACUTE {
            get {
                return ResourceManager.GetString("DEAD_DOUBLEACUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe50.
        /// </summary>
        internal static string DEAD_GRAVE {
            get {
                return ResourceManager.GetString("DEAD_GRAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5d.
        /// </summary>
        internal static string DEAD_IOTA {
            get {
                return ResourceManager.GetString("DEAD_IOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe54.
        /// </summary>
        internal static string DEAD_MACRON {
            get {
                return ResourceManager.GetString("DEAD_MACRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5c.
        /// </summary>
        internal static string DEAD_OGONEK {
            get {
                return ResourceManager.GetString("DEAD_OGONEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5f.
        /// </summary>
        internal static string DEAD_SEMIVOICED_SOUND {
            get {
                return ResourceManager.GetString("DEAD_SEMIVOICED_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe53.
        /// </summary>
        internal static string DEAD_TILDE {
            get {
                return ResourceManager.GetString("DEAD_TILDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xfe5e.
        /// </summary>
        internal static string DEAD_VOICED_SOUND {
            get {
                return ResourceManager.GetString("DEAD_VOICED_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffff.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65364.
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff57.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff0d.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff1b.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x20ac.
        /// </summary>
        internal static string EURO_SIGN {
            get {
                return ResourceManager.GetString("EURO_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffbe.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc7.
        /// </summary>
        internal static string F10 {
            get {
                return ResourceManager.GetString("F10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc8.
        /// </summary>
        internal static string F11 {
            get {
                return ResourceManager.GetString("F11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc9.
        /// </summary>
        internal static string F12 {
            get {
                return ResourceManager.GetString("F12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffca.
        /// </summary>
        internal static string F13 {
            get {
                return ResourceManager.GetString("F13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffcb.
        /// </summary>
        internal static string F14 {
            get {
                return ResourceManager.GetString("F14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffcc.
        /// </summary>
        internal static string F15 {
            get {
                return ResourceManager.GetString("F15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffcd.
        /// </summary>
        internal static string F16 {
            get {
                return ResourceManager.GetString("F16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffce.
        /// </summary>
        internal static string F17 {
            get {
                return ResourceManager.GetString("F17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffcf.
        /// </summary>
        internal static string F18 {
            get {
                return ResourceManager.GetString("F18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd0.
        /// </summary>
        internal static string F19 {
            get {
                return ResourceManager.GetString("F19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffbf.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd1.
        /// </summary>
        internal static string F20 {
            get {
                return ResourceManager.GetString("F20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd2.
        /// </summary>
        internal static string F21 {
            get {
                return ResourceManager.GetString("F21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd3.
        /// </summary>
        internal static string F22 {
            get {
                return ResourceManager.GetString("F22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd4.
        /// </summary>
        internal static string F23 {
            get {
                return ResourceManager.GetString("F23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffd5.
        /// </summary>
        internal static string F24 {
            get {
                return ResourceManager.GetString("F24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc0.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc1.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc2.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc3.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc4.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc5.
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffc6.
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff28.
        /// </summary>
        internal static string FULL_WIDTH {
            get {
                return ResourceManager.GetString("FULL_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff29.
        /// </summary>
        internal static string HALF_WIDTH {
            get {
                return ResourceManager.GetString("HALF_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff25.
        /// </summary>
        internal static string HIRAGANA {
            get {
                return ResourceManager.GetString("HIRAGANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff50.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff23.
        /// </summary>
        internal static string IMEConvert {
            get {
                return ResourceManager.GetString("IMEConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff22.
        /// </summary>
        internal static string IMENonconvert {
            get {
                return ResourceManager.GetString("IMENonconvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff21.
        /// </summary>
        internal static string INPUT_METHOD_ON_OFF {
            get {
                return ResourceManager.GetString("INPUT_METHOD_ON_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff63.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x00a1.
        /// </summary>
        internal static string INVERTED_EXCLAMATION_MARK {
            get {
                return ResourceManager.GetString("INVERTED_EXCLAMATION_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff25.
        /// </summary>
        internal static string JAPANESE_HIRAGANA {
            get {
                return ResourceManager.GetString("JAPANESE_HIRAGANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff26.
        /// </summary>
        internal static string JAPANESE_KATAKANA {
            get {
                return ResourceManager.GetString("JAPANESE_KATAKANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff24.
        /// </summary>
        internal static string JAPANESE_ROMAN {
            get {
                return ResourceManager.GetString("JAPANESE_ROMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff2e.
        /// </summary>
        internal static string KANA {
            get {
                return ResourceManager.GetString("KANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff2d.
        /// </summary>
        internal static string KanaMode {
            get {
                return ResourceManager.GetString("KanaMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff21.
        /// </summary>
        internal static string KanjiMode {
            get {
                return ResourceManager.GetString("KanjiMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff26.
        /// </summary>
        internal static string KATAKANA {
            get {
                return ResourceManager.GetString("KATAKANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65361.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffe9.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string NumLock {
            get {
                return ResourceManager.GetString("NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff56.
        /// </summary>
        internal static string PageDown {
            get {
                return ResourceManager.GetString("PageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff55.
        /// </summary>
        internal static string PageUp {
            get {
                return ResourceManager.GetString("PageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff13.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff3e.
        /// </summary>
        internal static string PREVIOUS_CANDIDATE {
            get {
                return ResourceManager.GetString("PREVIOUS_CANDIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff61.
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff55.
        /// </summary>
        internal static string Prior {
            get {
                return ResourceManager.GetString("Prior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65363.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff24.
        /// </summary>
        internal static string ROMAN_CHARACTERS {
            get {
                return ResourceManager.GetString("ROMAN_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff14.
        /// </summary>
        internal static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffac.
        /// </summary>
        internal static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xffe1.
        /// </summary>
        internal static string ShiftKey {
            get {
                return ResourceManager.GetString("ShiftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xff09.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65362.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
    }
}
