//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenOvf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenOvf.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto_Generated_{0}.
        /// </summary>
        public static string AUTOGENERATED {
            get {
                return ResourceManager.GetString("AUTOGENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is invalid..
        /// </summary>
        public static string CERTIFICATE_IS_INVALID {
            get {
                return ResourceManager.GetString("CERTIFICATE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compress {0}..
        /// </summary>
        public static string COMPRESS_FAILED {
            get {
                return ResourceManager.GetString("COMPRESS_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression method {0} is not supported..
        /// </summary>
        public static string COMPRESS_INVALID_METHOD {
            get {
                return ResourceManager.GetString("COMPRESS_INVALID_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert OVF to OVA..
        /// </summary>
        public static string CONVERSION_FAILED {
            get {
                return ResourceManager.GetString("CONVERSION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert HyperV configuration file..
        /// </summary>
        public static string CONVERSION_NO_DATA {
            get {
                return ResourceManager.GetString("CONVERSION_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string CULTURE_AVAILABLE {
            get {
                return ResourceManager.GetString("CULTURE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept or reject this EULA agreement..
        /// </summary>
        public static string EULA_ACCEPT_MESSAGE {
            get {
                return ResourceManager.GetString("EULA_ACCEPT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string EULA_CLOSE_BUTTON {
            get {
                return ResourceManager.GetString("EULA_CLOSE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string EULA_RB_ACCEPT {
            get {
                return ResourceManager.GetString("EULA_RB_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string EULA_RB_REJECT {
            get {
                return ResourceManager.GetString("EULA_RB_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Citrix] OVF EULA.
        /// </summary>
        public static string EULA_TITLE {
            get {
                return ResourceManager.GetString("EULA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add operating system section because the virtual system collection is invalid..
        /// </summary>
        public static string FAILED_TO_ADD_OS_SECTION {
            get {
                return ResourceManager.GetString("FAILED_TO_ADD_OS_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add virtual hardware section because the virtual system collection is invalid..
        /// </summary>
        public static string FAILED_TO_ADD_VIRTUAL_HARDWARE_SECTION {
            get {
                return ResourceManager.GetString("FAILED_TO_ADD_VIRTUAL_HARDWARE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find {0}..
        /// </summary>
        public static string FILE_MISSING {
            get {
                return ResourceManager.GetString("FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get next file in OVA..
        /// </summary>
        public static string INVALID_DATA_IN_OVA {
            get {
                return ResourceManager.GetString("INVALID_DATA_IN_OVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize OVF descriptor..
        /// </summary>
        public static string INVALID_DATA_IN_OVF {
            get {
                return ResourceManager.GetString("INVALID_DATA_IN_OVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find section with type {0} and id {1}..
        /// </summary>
        public static string OVF_CANNOT_FIND_SECTION {
            get {
                return ResourceManager.GetString("OVF_CANNOT_FIND_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read EULA..
        /// </summary>
        public static string OVF_CANNOT_READ_EULA {
            get {
                return ResourceManager.GetString("OVF_CANNOT_READ_EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find DVD or CD drive resource..
        /// </summary>
        public static string OVF_CDROM_MISSING {
            get {
                return ResourceManager.GetString("OVF_CDROM_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompressed OVA file does not have an ova extension..
        /// </summary>
        public static string OVF_COMPRESSED_OVA_INVALID {
            get {
                return ResourceManager.GetString("OVF_COMPRESSED_OVA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find controller {0}..
        /// </summary>
        public static string OVF_CONTROLLER_MISSING {
            get {
                return ResourceManager.GetString("OVF_CONTROLLER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open {0}..
        /// </summary>
        public static string OVF_COULD_NOT_OPEN_STREAM {
            get {
                return ResourceManager.GetString("OVF_COULD_NOT_OPEN_STREAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find deployment configuration section..
        /// </summary>
        public static string OVF_DEPLOYMENT_CFG_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_DEPLOYMENT_CFG_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find deployment section..
        /// </summary>
        public static string OVF_DEPLOYMENT_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_DEPLOYMENT_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device number {0} is less than zero or greater than 15..
        /// </summary>
        public static string OVF_DEVICE_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("OVF_DEVICE_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the disk section..
        /// </summary>
        public static string OVF_DISK_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_DISK_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF envelope is invalid..
        /// </summary>
        public static string OVF_ENVELOPE_IS_INVALID {
            get {
                return ResourceManager.GetString("OVF_ENVELOPE_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the install section..
        /// </summary>
        public static string OVF_INSTALL_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_INSTALL_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the post-install section..
        /// </summary>
        public static string OVF_POST_INSTALL_MISSING {
            get {
                return ResourceManager.GetString("OVF_POST_INSTALL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find a post-install operation..
        /// </summary>
        public static string OVF_POST_INSTALL_OPERATION_MISSING {
            get {
                return ResourceManager.GetString("OVF_POST_INSTALL_OPERATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find product property {0}..
        /// </summary>
        public static string OVF_PRODUCT_PROPERTY_MISSING {
            get {
                return ResourceManager.GetString("OVF_PRODUCT_PROPERTY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find product section {0}..
        /// </summary>
        public static string OVF_PRODUCT_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_PRODUCT_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find resource {0}..
        /// </summary>
        public static string OVF_RASD_MISSING {
            get {
                return ResourceManager.GetString("OVF_RASD_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the references section..
        /// </summary>
        public static string OVF_REFERENCE_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_REFERENCE_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the startup section..
        /// </summary>
        public static string OVF_STARTUP_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_STARTUP_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the strings section for lanugage {0}..
        /// </summary>
        public static string OVF_STRINGS_SECTION_MISSING {
            get {
                return ResourceManager.GetString("OVF_STRINGS_SECTION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find string {0} for language {1}..
        /// </summary>
        public static string OVF_STRINGS_SECTION_MISSING_MSG {
            get {
                return ResourceManager.GetString("OVF_STRINGS_SECTION_MISSING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the virtual hardware section..
        /// </summary>
        public static string OVF_VHS_MISSING {
            get {
                return ResourceManager.GetString("OVF_VHS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the virtual system..
        /// </summary>
        public static string OVF_VIRTUAL_SYSTEM_MISSING {
            get {
                return ResourceManager.GetString("OVF_VIRTUAL_SYSTEM_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is empty..
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is invalid..
        /// </summary>
        public static string PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PASSWORD_NOMATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enter:.
        /// </summary>
        public static string PASSWORD_REENTER {
            get {
                return ResourceManager.GetString("PASSWORD_REENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair;.
        /// </summary>
        public static string PASSWORD_STRENGTH_FAIR {
            get {
                return ResourceManager.GetString("PASSWORD_STRENGTH_FAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good;.
        /// </summary>
        public static string PASSWORD_STRENGTH_GOOD {
            get {
                return ResourceManager.GetString("PASSWORD_STRENGTH_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low;.
        /// </summary>
        public static string PASSWORD_STRENGTH_LOW {
            get {
                return ResourceManager.GetString("PASSWORD_STRENGTH_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Strength: .
        /// </summary>
        public static string PASSWORD_STRENGTH_PROMPT {
            get {
                return ResourceManager.GetString("PASSWORD_STRENGTH_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong;.
        /// </summary>
        public static string PASSWORD_STRENGTH_STRONG {
            get {
                return ResourceManager.GetString("PASSWORD_STRENGTH_STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is valid..
        /// </summary>
        public static string PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password;.
        /// </summary>
        public static string PASSWORD_TITLE {
            get {
                return ResourceManager.GetString("PASSWORD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not strong enough..
        /// </summary>
        public static string PASSWORD_TOO_WEAK {
            get {
                return ResourceManager.GetString("PASSWORD_TOO_WEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information:.
        /// </summary>
        public static string PRODUCT_INFO_PROMPT {
            get {
                return ResourceManager.GetString("PRODUCT_INFO_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string PRODUCT_PROMPT {
            get {
                return ResourceManager.GetString("PRODUCT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product URL:.
        /// </summary>
        public static string PRODUCT_URL_PROMPT {
            get {
                return ResourceManager.GetString("PRODUCT_URL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded..
        /// </summary>
        public static string RESOURCES_LOADED {
            get {
                return ResourceManager.GetString("RESOURCES_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Failure.
        /// </summary>
        public static string SECURITY_FAILURE {
            get {
                return ResourceManager.GetString("SECURITY_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find files listed in the manifest. Please refer to the log for the list of missing files..
        /// </summary>
        public static string SECURITY_FILE_MISSING {
            get {
                return ResourceManager.GetString("SECURITY_FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security method {0} is not supported..
        /// </summary>
        public static string SECURITY_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("SECURITY_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security section is invalid..
        /// </summary>
        public static string SECURITY_SECTION_INVALID {
            get {
                return ResourceManager.GetString("SECURITY_SECTION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not match the original..
        /// </summary>
        public static string SECURITY_SIGNATURE_FAILED {
            get {
                return ResourceManager.GetString("SECURITY_SIGNATURE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF package {0} is invalid..
        /// </summary>
        public static string VALIDATION_FAILURE {
            get {
                return ResourceManager.GetString("VALIDATION_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find file {0} listed in the reference section..
        /// </summary>
        public static string VALIDATION_FILE_NOTFOUND {
            get {
                return ResourceManager.GetString("VALIDATION_FILE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor quantity {0} exceeds the limit of {1}..
        /// </summary>
        public static string VALIDATION_INVALID_CPU_EXCEEDS_LIMIT {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_CPU_EXCEEDS_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor quantity {0} is invalid..
        /// </summary>
        public static string VALIDATION_INVALID_CPU_QUANTITY {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_CPU_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} has an unsupported extension..
        /// </summary>
        public static string VALIDATION_INVALID_FILETYPE {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceId is empty..
        /// </summary>
        public static string VALIDATION_INVALID_INSTANCEID {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_INSTANCEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation unit is invalid..
        /// </summary>
        public static string VALIDATION_INVALID_MEMORY_ALLOCATIONUNITS {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_MEMORY_ALLOCATIONUNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory quantity is invalid..
        /// </summary>
        public static string VALIDATION_INVALID_MEMORY_QUANTITY {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_MEMORY_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF envelope item has an unknown type..
        /// </summary>
        public static string VALIDATION_INVALID_TYPE {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF version number {0} is invalid..
        /// </summary>
        public static string VALIDATION_INVALID_VERSION {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A network is not connected to a device..
        /// </summary>
        public static string VALIDATION_NETWORK_NO_DEVICE {
            get {
                return ResourceManager.GetString("VALIDATION_NETWORK_NO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required resource with id {0} and name {1} was not recognized..
        /// </summary>
        public static string VALIDATION_REQUIRED_ELEMENT_NOT_RECOGNIZED {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_ELEMENT_NOT_RECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVF descriptor is invalid..
        /// </summary>
        public static string VALIDATION_SCHEMA_FAILED {
            get {
                return ResourceManager.GetString("VALIDATION_SCHEMA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual hardware type {0} is invalid..
        /// </summary>
        public static string VALIDATION_UNKNOWN_HARDWARE_TYPE {
            get {
                return ResourceManager.GetString("VALIDATION_UNKNOWN_HARDWARE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor:.
        /// </summary>
        public static string VENDOR_PROMPT {
            get {
                return ResourceManager.GetString("VENDOR_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor URL:.
        /// </summary>
        public static string VENDOR_URL_PROMPT {
            get {
                return ResourceManager.GetString("VENDOR_URL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VERSION_PROMPT {
            get {
                return ResourceManager.GetString("VERSION_PROMPT", resourceCulture);
            }
        }
    }
}
