//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XenOvfTransport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XenOvfTransport.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliances.
        /// </summary>
        internal static string APPLIANCE_FOLDER_PATH {
            get {
                return ResourceManager.GetString("APPLIANCE_FOLDER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD/DVD Drive.
        /// </summary>
        internal static string CD_DVD_DEVICE {
            get {
                return ResourceManager.GetString("CD_DVD_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete.
        /// </summary>
        internal static string COMPLETE {
            get {
                return ResourceManager.GetString("COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed export..
        /// </summary>
        internal static string COMPLETED_EXPORT {
            get {
                return ResourceManager.GetString("COMPLETED_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed import..
        /// </summary>
        internal static string COMPLETED_IMPORT {
            get {
                return ResourceManager.GetString("COMPLETED_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        internal static string CULTURE_AVAILABLE {
            get {
                return ResourceManager.GetString("CULTURE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from an OVF/OVA package..
        /// </summary>
        internal static string DEFAULT_IMPORT_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEFAULT_IMPORT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported from a virtual disk file..
        /// </summary>
        internal static string DEFAULT_IMPORTED_DISK_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEFAULT_IMPORTED_DISK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached {0}..
        /// </summary>
        internal static string DEVICE_ATTACHED {
            get {
                return ResourceManager.GetString("DEVICE_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk Image.
        /// </summary>
        internal static string DISK_DEVICE {
            get {
                return ResourceManager.GetString("DISK_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add resource {0}..
        /// </summary>
        internal static string ERROR_ADDRESOURCESETTINGDATA_FAILED {
            get {
                return ResourceManager.GetString("ERROR_ADDRESOURCESETTINGDATA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create VDI..
        /// </summary>
        internal static string ERROR_CANNOT_CREATE_VDI {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CREATE_VDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage repository was not found and a default was not assigned..
        /// </summary>
        internal static string ERROR_COULD_NOT_FIND_SR {
            get {
                return ResourceManager.GetString("ERROR_COULD_NOT_FIND_SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a virtual block device (VBD)..
        /// </summary>
        internal static string ERROR_CREATE_VBD_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CREATE_VBD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a virtual network interface (VIF)..
        /// </summary>
        internal static string ERROR_CREATE_VIF_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CREATE_VIF_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a virtual machine (VM)..
        /// </summary>
        internal static string ERROR_CREATE_VM_FAILED {
            get {
                return ResourceManager.GetString("ERROR_CREATE_VM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreements were not accepted..
        /// </summary>
        internal static string ERROR_EULAS_NOT_ACCEPTED {
            get {
                return ResourceManager.GetString("ERROR_EULAS_NOT_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export..
        /// </summary>
        internal static string ERROR_EXPORT_FAILED {
            get {
                return ResourceManager.GetString("ERROR_EXPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to import was not provided..
        /// </summary>
        internal static string ERROR_FILE_NAME_NULL {
            get {
                return ResourceManager.GetString("ERROR_FILE_NAME_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import a virtual disk over HTTP..
        /// </summary>
        internal static string ERROR_HTTP_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("ERROR_HTTP_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import virtual disk from file {0} to storage repository {1}..
        /// </summary>
        internal static string ERROR_IMPORT_DISK_FAILED {
            get {
                return ResourceManager.GetString("ERROR_IMPORT_DISK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import..
        /// </summary>
        internal static string ERROR_IMPORT_FAILED {
            get {
                return ResourceManager.GetString("ERROR_IMPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import a virtual disk over iSCSI..
        /// </summary>
        internal static string ERROR_ISCSI_UPLOAD_FAILED {
            get {
                return ResourceManager.GetString("ERROR_ISCSI_UPLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password was not provided to decrypt an OVF package..
        /// </summary>
        internal static string ERROR_NO_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_NO_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from [XenServer]..
        /// </summary>
        internal static string ERROR_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("ERROR_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove a virtual disk image (VDI)..
        /// </summary>
        internal static string ERROR_REMOVE_VDI_FAILED {
            get {
                return ResourceManager.GetString("ERROR_REMOVE_VDI_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove a virtual machine (VM)..
        /// </summary>
        internal static string ERROR_REMOVE_VM_FAILED {
            get {
                return ResourceManager.GetString("ERROR_REMOVE_VM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find virtual machine {0}..
        /// </summary>
        internal static string ERROR_VM_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_VM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please shutdown or suspend virtual machine {0} before exporting..
        /// </summary>
        internal static string ERROR_VM_NOT_HALTED {
            get {
                return ResourceManager.GetString("ERROR_VM_NOT_HALTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export: .
        /// </summary>
        internal static string EXPORT_PROMPT {
            get {
                return ResourceManager.GetString("EXPORT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string FAILURE_PROMPT {
            get {
                return ResourceManager.GetString("FAILURE_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find {0}..
        /// </summary>
        internal static string FILE_MISSING {
            get {
                return ResourceManager.GetString("FILE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import virtual disk file..
        /// </summary>
        internal static string FILE_TRANSPORT_FAILED {
            get {
                return ResourceManager.GetString("FILE_TRANSPORT_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting virtual disk {0} ... .
        /// </summary>
        internal static string FILES_TRANSPORT_CLEANUP {
            get {
                return ResourceManager.GetString("FILES_TRANSPORT_CLEANUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting virtual disk {0} ... .
        /// </summary>
        internal static string FILES_TRANSPORT_SETUP {
            get {
                return ResourceManager.GetString("FILES_TRANSPORT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import: .
        /// </summary>
        internal static string IMPORT_PROMPT {
            get {
                return ResourceManager.GetString("IMPORT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled transfer of virtual disk {0}..
        /// </summary>
        internal static string ISCSI_COPY_CANCELLED {
            get {
                return ResourceManager.GetString("ISCSI_COPY_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer virtual disk {0}..
        /// </summary>
        internal static string ISCSI_COPY_ERROR {
            get {
                return ResourceManager.GetString("ISCSI_COPY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring virtual disk {0} ... .
        /// </summary>
        internal static string ISCSI_COPY_PROGRESS {
            get {
                return ResourceManager.GetString("ISCSI_COPY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to virtual disk over iSCSI..
        /// </summary>
        internal static string ISCSI_ERROR {
            get {
                return ResourceManager.GetString("ISCSI_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open virtual disk..
        /// </summary>
        internal static string ISCSI_ERROR_CANNOT_OPEN_DISK {
            get {
                return ResourceManager.GetString("ISCSI_ERROR_CANNOT_OPEN_DISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of the Transfer VM is unknown..
        /// </summary>
        internal static string ISCSI_ERROR_NO_IPADDRESS {
            get {
                return ResourceManager.GetString("ISCSI_ERROR_NO_IPADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to shutdown Transfer VM..
        /// </summary>
        internal static string ISCSI_SHUTDOWN_ERROR {
            get {
                return ResourceManager.GetString("ISCSI_SHUTDOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Transfer VM..
        /// </summary>
        internal static string ISCSI_START_ERROR {
            get {
                return ResourceManager.GetString("ISCSI_START_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled virtual disk verification after export..
        /// </summary>
        internal static string ISCSI_VERIFY_CANCELLED {
            get {
                return ResourceManager.GetString("ISCSI_VERIFY_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to verify virtual disk {0}..
        /// </summary>
        internal static string ISCSI_VERIFY_ERROR {
            get {
                return ResourceManager.GetString("ISCSI_VERIFY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exported virtual disk does not match the source..
        /// </summary>
        internal static string ISCSI_VERIFY_INVALID {
            get {
                return ResourceManager.GetString("ISCSI_VERIFY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying disk {0} ... .
        /// </summary>
        internal static string ISCSI_VERIFY_PROGRESS {
            get {
                return ResourceManager.GetString("ISCSI_VERIFY_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring file {0} of {1}, {2}, from WIM ... .
        /// </summary>
        internal static string ISCSI_WIM_PROGRESS_FORMAT {
            get {
                return ResourceManager.GetString("ISCSI_WIM_PROGRESS_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        internal static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage repository {0} does not have {1} bytes of free space to import virtual disk {2}..
        /// </summary>
        internal static string NOT_ENOUGH_SPACE_IN_SR {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_SPACE_IN_SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting {0} ... .
        /// </summary>
        internal static string START_FILE_DECRYPTION {
            get {
                return ResourceManager.GetString("START_FILE_DECRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding {0} ... .
        /// </summary>
        internal static string START_FILE_EXPANSION {
            get {
                return ResourceManager.GetString("START_FILE_EXPANSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring virtual machine for [XenServer] ... .
        /// </summary>
        internal static string START_POST_INSTALL_INSTRUCTIONS {
            get {
                return ResourceManager.GetString("START_POST_INSTALL_INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported..
        /// </summary>
        internal static string UNDEFINED_NAME_LABEL {
            get {
                return ResourceManager.GetString("UNDEFINED_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer type is not supported..
        /// </summary>
        internal static string UNSUPPORTED_TRANSPORT {
            get {
                return ResourceManager.GetString("UNSUPPORTED_TRANSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please view the log for details about a failure to import..
        /// </summary>
        internal static string WARNING_ADMIN_REQUIRED {
            get {
                return ResourceManager.GetString("WARNING_ADMIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imported virtual machine is not bootable because a master boot record was not found..
        /// </summary>
        internal static string WARNING_TARGET_NOT_BOOTABLE {
            get {
                return ResourceManager.GetString("WARNING_TARGET_NOT_BOOTABLE", resourceCulture);
            }
        }
    }
}
